# Generated by Django 3.2.9 on 2021-11-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(help_text='primary key', primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(help_text='primary key', primary_key=True, serialize=False)),
                ('key', models.TextField()),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'table',
            },
        ),
    ]
